version: '3'
services:
  client:
    build: ./client
    ports: 
      - 5173:5173
    container_name: react-express-client-prod
    depends_on:
      - server
  server:
    build: ./server
    ports:
      - 3001:3001
    container_name: react-express-server-prod
