BEGIN TRANSACTION;
CREATE TABLE IF NOT EXISTS "FOLLOWED_ORGA" (
	"idOrga"	INTEGER NOT NULL,
	"IdUser"	INTEGER NOT NULL,
	PRIMARY KEY("idOrga","IdUser"),
	FOREIGN KEY("idOrga") REFERENCES "ORGANIZATIONS"("idOrga"),
	FOREIGN KEY("IdUser") REFERENCES "USERS"("idUser")
);
CREATE TABLE IF NOT EXISTS "GAMES" (
	"idGame"	INTEGER NOT NULL UNIQUE,
	"idTopic"	INTEGER NOT NULL,
	"idUser"	INTEGER NOT NULL,
	"score"	REAL NOT NULL,
	PRIMARY KEY("idGame" AUTOINCREMENT),
	FOREIGN KEY("idUser") REFERENCES "USERS"("idUser"),
	FOREIGN KEY("idTopic") REFERENCES "TOPICS"("idTopic")
);
CREATE TABLE IF NOT EXISTS "LINK_TOPIC_ORGA" (
	"idOrga"	INTEGER NOT NULL,
	"idTopic"	INTEGER NOT NULL,
	PRIMARY KEY("idOrga","idTopic"),
	FOREIGN KEY("idOrga") REFERENCES "ORGANIZATIONS"("idOrga"),
	FOREIGN KEY("idTopic") REFERENCES "TOPICS"("idTopic")
);
CREATE TABLE IF NOT EXISTS "ORGANIZATIONS" (
	"idOrga"	INTEGER NOT NULL UNIQUE,
	"title"	TEXT NOT NULL,
	"description"	TEXT,
	"idUser"	INTEGER NOT NULL,
	PRIMARY KEY("idOrga"),
	FOREIGN KEY("idUser") REFERENCES "USERS"("idUser")
);
CREATE TABLE IF NOT EXISTS "TOPICS" (
	"idTopic"	INTEGER NOT NULL UNIQUE,
	"title"	TEXT NOT NULL,
	"description"	TEXT,
	"idUser"	INTEGER NOT NULL,
	PRIMARY KEY("idTopic" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "USERS" (
	"idUser"	INTEGER UNIQUE,
	"mail"	VARCHAR(255) UNIQUE,
	"password"	VARCHAR(255),
	"pseudo"	VARCHAR(255),
	PRIMARY KEY("idUser" AUTOINCREMENT)
);
CREATE TABLE IF NOT EXISTS "WORDS" (
	"idWord"	INTEGER NOT NULL UNIQUE,
	"word_en"	TEXT NOT NULL,
	"word_fr"	TEXT NOT NULL,
	"idTopic"	INTEGER NOT NULL,
	PRIMARY KEY("idWord" AUTOINCREMENT),
	FOREIGN KEY("idTopic") REFERENCES "TOPICS"("idTopic")
);

